from pathlib import Path

Path(Path.cwd() / "setup.py").touch(exist_ok=True)
Path(Path.cwd() / "config").mkdir(exist_ok=True)
Path(Path.cwd() / "config" / "const.py").touch(exist_ok=True)
Path(Path.cwd() / "config" / "logger.py").touch(exist_ok=True)
Path(Path.cwd() / "notebooks").mkdir(exist_ok=True)
Path(Path.cwd() / "input").mkdir(exist_ok=True, parents=True)
Path(Path.cwd() / "models").mkdir(exist_ok=True)
Path(Path.cwd() / "src" / "data").mkdir(exist_ok=True, parents=True)
Path(Path.cwd() / "src" / "features").mkdir(exist_ok=True)
Path(Path.cwd() / "src" / "models").mkdir(exist_ok=True)
Path(Path.cwd() / "src" / "visualization").mkdir(exist_ok=True)
Path(Path.cwd() / "reports" / "figures").mkdir(exist_ok=True, parents=True)
Path(Path.cwd() / "reports" / "results").mkdir(exist_ok=True)
Path(Path.cwd() / "logs").mkdir(exist_ok=True)
